from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.dependencies import get_current_user, get_db, require_role
from app.models import User, UserRole
from app.schema.user import UserRead, Token, UserCreate
from app.security import create_access_token, verify_password, hash_password

router = APIRouter(prefix="/auth", tags=["auth"])

@router.post("/token", response_model=Token)
async def login(
    form_data : OAuth2PasswordRequestForm = Depends(),
    db : AsyncSession = Depends(get_db)
)->Token:
    username = form_data.username.strip().lower()
    result = await db.execute(select(User).where(func.lower(User.username) == username))
    user = result.scalar_one_or_none()

    if user is None or not verify_password(user.hashed_password, form_data.password):
        raise HTTPException(
            detail="Incorrect username or password",
            status_code=status.HTTP_401_UNAUTHORIZED,
            headers = {"WWW-Authenticate" : "Bearer"}
        )
    access_token = create_access_token(data = {"sub": user.username, "role": user.role.value})
    return Token(access_token=access_token, token_type="bearer")

# function to register our new user. this endpoint is protected by the require_role dependency, which
# will require the user to have the OPERATIONS_ADMIN role
@router.post("/register", response_model=UserRead, status_code=status.HTTP_201_CREATED)
async def register_user(
    payload : UserCreate,
    db : AsyncSession = Depends(get_db),
    _ : User = Depends(require_role(UserRole.ADMIN))
)-> User:
    # can add other validation here (require certain characters in the password, etc.) if you want...
    # could also would add to database and front-end to get 3 layers of validation...

    
    # checking to see if username already exists in the database
    username = payload.username.strip().lower()
    existing = await db.execute(select(User).where(func.lower(User.username) == username))
    if existing.scalar_one_or_none() is not None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(f"Username {payload.username} is already taken")
        )
    # create a new User object with the provided username, hashed password, and UserRole
    user = User(
        username=username,
        hashed_password=hash_password(payload.password),
        first_name=payload.first_name,
        last_name=payload.last_name,
        role=payload.role,
        facility_id=payload.facility_id
    )

    # add the new user object to the db
    db.add(user)
    # commit the db transaction
    await db.commit()
    # refresh the user so we get the id generated by the db
    await db.refresh(user)
    return user